import { FormEvent, useRef, useState } from 'react'
import { Bot, LoaderCircle, Send, Wrench } from 'lucide-react'
import Markdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { agentApi, type AgentEvent } from '../services/api'

type Message = { role: 'user' | 'assistant'; text: string; events?: AgentEvent[] }
export default function AssistantPage() {
  const [messages, setMessages] = useState<Message[]>([]); const [prompt, setPrompt] = useState(''); const [running, setRunning] = useState(false); const abort = useRef<AbortController>()
  const submit = async (event: FormEvent) => { event.preventDefault(); const text = prompt.trim(); if (!text || running) return; setPrompt(''); setMessages(current => [...current, { role: 'user', text }, { role: 'assistant', text: '', events: [] }]); setRunning(true); abort.current = new AbortController(); try { await agentApi.chat(text, update => setMessages(current => { const next = [...current]; const last = next[next.length - 1]; if (update.type === 'text') last.text += update.text ?? ''; else last.events = [...(last.events ?? []), update]; return next }), abort.current.signal) } catch (error) { setMessages(current => { const next = [...current]; next[next.length - 1].text += `\n\n${error instanceof Error ? error.message : 'Agent request failed'}`; return next }) } finally { setRunning(false) } }
  return <div className="mx-auto flex h-full max-w-5xl flex-col px-4 py-6 sm:px-6"><div className="mb-5 flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary-600 text-white"><Bot className="h-5 w-5" /></div><div><h1 className="text-lg font-semibold">API Flow Assistant</h1><p className="text-sm text-slate-500">Inspect and change API Flow through its MCP tools.</p></div></div><div className="flex-1 space-y-4 overflow-y-auto pb-5">{messages.length === 0 && <div className="border border-dashed border-slate-300 p-6 text-sm text-slate-500 dark:border-slate-700">Ask about a specification, flow, template, release, session, or trace.</div>}{messages.map((message, index) => <div key={index} className={message.role === 'user' ? 'ml-auto max-w-3xl bg-primary-600 p-3 text-sm text-white' : 'max-w-3xl border border-slate-200 bg-white p-4 text-sm dark:border-slate-800 dark:bg-slate-900'}>{message.role === 'assistant' ? <Markdown remarkPlugins={[remarkGfm]}>{message.text}</Markdown> : message.text}{message.events?.map((item, eventIndex) => <div key={eventIndex} className="mt-2 flex items-center gap-2 border-l-2 border-primary-400 pl-2 text-xs text-slate-500"><Wrench className="h-3.5 w-3.5" />{item.type === 'tool_start' ? `Calling ${item.tool}` : `${item.tool ?? 'Tool'} completed`}</div>)}</div>)}</div><form onSubmit={submit} className="flex gap-2 border-t border-slate-200 pt-4 dark:border-slate-800"><textarea value={prompt} onChange={event => setPrompt(event.target.value)} className="min-h-11 flex-1 resize-none border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:border-primary-500 dark:border-slate-700 dark:bg-slate-900" placeholder="Ask the assistant..." /><button type="submit" className="inline-flex h-11 w-11 items-center justify-center bg-primary-600 text-white disabled:opacity-50" disabled={!prompt.trim() || running} aria-label="Send message">{running ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}</button></form></div>
}
